### ISSUE TITLE
New stats organization for compute

### ISSUE THREAD

**Issue by marcaurele** [exoscale/collectd-python-extra#11]
Proposal for the new stats organization for:

### capacity > zone-name > pod-name > cluster-name > host-name > vm-state > so
For each level, have those values:
- VM total

### capacity > zone-name > pod-name > cluster-name > host-name
For each level, have those values:
- cpu allocated
- disk size allocated
- disk size total
- disk size used
- memory allocated
- memory total
- memory used
- VM total

### capacity > zone-name
- activeviewersessions

### account
- disabled
- enabled
- total

**Comment by llambiel** [comment]
Quid Secondary storage ?

**Comment by llambiel** [comment]
IP addresses ?

**Comment by llambiel** [comment]
I would add also add the tags. ex 0=public 1=GPU 2=dedicated etc...

**Comment by llambiel** [comment]
Also add the number of hosts at each level
